version: "3"

services:
  laravel:
    build:
      context: ../docker/laravel
      dockerfile: Dockerfile.prod
    image: danaraujo89/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ../docker/nginx
      dockerfile: Dockerfile.prod
    image: danaraujo89/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
